-- WarrantyPass phase 2: offchain product and warranty records.
--
-- Ownership model
-- ---------------
-- Rows are owned by a Supabase auth user (`auth.uid()`). In phase 2 that user
-- is an *anonymous* session created by `signInAnonymously()`. A connected
-- Ethereum wallet is deliberately NOT an authorization identity here: a wallet
-- connection in the browser does not prove wallet ownership to Postgres. Wallet
-- or email linking is a later phase, and will map an existing anonymous user to
-- a stronger identity rather than replacing this model.
--
-- Privacy
-- -------
-- Serial numbers, prices, retailers and purchase dates are private to the
-- owner. Nothing here is readable by `anon`; the public `/verify/:id` route
-- will be built later on an explicit, separate public projection of safe
-- fields. Do not add an `anon` policy to these tables.

-- ---------------------------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------------------------

-- Reusable trigger function. Trigger functions cannot be invoked over
-- PostgREST (the argument and return types do not map), so living in `public`
-- does not expose it as an RPC.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'Trigger function: stamps updated_at on every UPDATE.';

-- ---------------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------------

create table public.products (
  id uuid primary key default gen_random_uuid(),

  user_id uuid not null references auth.users (id) on delete cascade,

  -- Opaque, randomly generated identifier. Never derived from serial number,
  -- model, email, wallet address or user name, so it cannot be guessed from
  -- anything visible about the product. Generated by
  -- create_product_with_warranty(); the format check keeps it that way.
  public_id text not null unique,

  brand text not null,
  model text not null,
  serial_number text,
  retailer text,
  purchase_date date not null,
  purchase_price numeric(12, 2),
  currency text not null default 'USD',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint products_brand_not_blank check (length(btrim(brand)) > 0),
  constraint products_brand_length check (length(brand) <= 120),
  constraint products_model_not_blank check (length(btrim(model)) > 0),
  constraint products_model_length check (length(model) <= 120),

  constraint products_public_id_format check (public_id ~ '^wp_[0-9a-f]{32}$'),

  constraint products_serial_number_not_blank check (
    serial_number is null or length(btrim(serial_number)) > 0
  ),
  constraint products_serial_number_length check (
    serial_number is null or length(serial_number) <= 120
  ),
  constraint products_retailer_not_blank check (
    retailer is null or length(btrim(retailer)) > 0
  ),
  constraint products_retailer_length check (
    retailer is null or length(retailer) <= 120
  ),

  constraint products_purchase_price_non_negative check (
    purchase_price is null or purchase_price >= 0
  ),

  -- Short ISO-4217-style code, e.g. USD, EUR, GBP.
  constraint products_currency_format check (currency ~ '^[A-Z]{3}$')
);

comment on table public.products is
  'A product owned by a WarrantyPass user. Private to its owner via RLS.';
comment on column public.products.public_id is
  'Opaque random identifier (wp_<32 hex>). Not derived from product data.';
comment on column public.products.serial_number is
  'Private. Must never be exposed on a public route or in a public projection.';

-- Serves both the RLS predicate (user_id) and the dashboard ordering
-- (created_at desc) in one index. `public_id` needs no separate index: its
-- UNIQUE constraint already creates one.
create index products_user_id_created_at_idx
  on public.products (user_id, created_at desc);

create trigger products_set_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- warranties
-- ---------------------------------------------------------------------------

create table public.warranties (
  id uuid primary key default gen_random_uuid(),

  -- UNIQUE: exactly one primary warranty per product in phase 2. Multiple
  -- protection plans, if ever needed, are a schema change made deliberately.
  -- The UNIQUE constraint also provides the foreign-key index.
  product_id uuid not null unique references public.products (id) on delete cascade,

  issuer text,
  start_date date not null,
  end_date date not null,

  -- Three-valued on purpose. A boolean cannot express "the user does not know
  -- the manufacturer's policy", and guessing would be worse than admitting it.
  transferability text not null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint warranties_transferability_allowed check (
    transferability in ('transferable', 'non_transferable', 'unknown')
  ),
  constraint warranties_end_on_or_after_start check (end_date >= start_date),
  constraint warranties_issuer_not_blank check (
    issuer is null or length(btrim(issuer)) > 0
  ),
  constraint warranties_issuer_length check (
    issuer is null or length(issuer) <= 120
  )
);

comment on table public.warranties is
  'The primary warranty for a product. Status (active/expiring/expired) is '
  'derived from end_date in the application, never stored, so it cannot go stale.';

create trigger warranties_set_updated_at
  before update on public.warranties
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.products enable row level security;
alter table public.warranties enable row level security;

-- Supabase grants table privileges to `anon` and `authenticated` by default.
-- RLS with no `anon` policy would already deny anonymous (unauthenticated)
-- access, but revoking is defence in depth and makes the intent reviewable.
revoke all on table public.products from anon;
revoke all on table public.warranties from anon;

grant select, insert, update, delete on table public.products to authenticated;
grant select, insert, update, delete on table public.warranties to authenticated;

-- `auth.uid()` is wrapped in a scalar subquery throughout so Postgres
-- evaluates it once per statement instead of once per row.

create policy products_select_own on public.products
  for select to authenticated
  using (user_id = (select auth.uid()));

-- WITH CHECK on insert is what stops a client submitting someone else's
-- user_id: the row must be owned by the caller or the insert is rejected.
create policy products_insert_own on public.products
  for insert to authenticated
  with check (user_id = (select auth.uid()));

-- USING selects which rows may be updated; WITH CHECK stops an update from
-- reassigning a row to a different owner.
create policy products_update_own on public.products
  for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));

create policy products_delete_own on public.products
  for delete to authenticated
  using (user_id = (select auth.uid()));

-- Warranty access is derived entirely from product ownership: there is no
-- user_id column to keep in sync, so a warranty can never disagree with its
-- product about who owns it.

create policy warranties_select_own on public.warranties
  for select to authenticated
  using (
    exists (
      select 1
      from public.products p
      where p.id = warranties.product_id
        and p.user_id = (select auth.uid())
    )
  );

create policy warranties_insert_own on public.warranties
  for insert to authenticated
  with check (
    exists (
      select 1
      from public.products p
      where p.id = warranties.product_id
        and p.user_id = (select auth.uid())
    )
  );

create policy warranties_update_own on public.warranties
  for update to authenticated
  using (
    exists (
      select 1
      from public.products p
      where p.id = warranties.product_id
        and p.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1
      from public.products p
      where p.id = warranties.product_id
        and p.user_id = (select auth.uid())
    )
  );

create policy warranties_delete_own on public.warranties
  for delete to authenticated
  using (
    exists (
      select 1
      from public.products p
      where p.id = warranties.product_id
        and p.user_id = (select auth.uid())
    )
  );

-- ---------------------------------------------------------------------------
-- Atomic creation
-- ---------------------------------------------------------------------------

-- Creating a WarrantyPass writes two rows. Doing that as two REST calls can
-- leave a product with no warranty if the second call fails. This function
-- runs both inserts in one transaction, so either both land or neither does.
--
-- SECURITY INVOKER (the default, stated explicitly): the function runs as the
-- calling user, so both inserts are still checked by the RLS policies above.
-- There is no need for SECURITY DEFINER here, and using it would mean
-- re-implementing those checks by hand inside the function body.
--
-- The owner is taken from auth.uid() and never from an argument, so a client
-- has no way to create a product for another user.
create or replace function public.create_product_with_warranty(
  p_brand text,
  p_model text,
  p_purchase_date date,
  p_warranty_start_date date,
  p_warranty_end_date date,
  p_transferability text,
  p_serial_number text default null,
  p_retailer text default null,
  p_purchase_price numeric default null,
  p_currency text default 'USD',
  p_warranty_issuer text default null
)
returns table (product_id uuid, public_id text)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_public_id text := 'wp_' || replace(gen_random_uuid()::text, '-', '');
  v_product_id uuid;
begin
  if v_user_id is null then
    raise exception 'An authenticated session is required to create a product'
      using errcode = '42501';
  end if;

  insert into public.products (
    user_id, public_id, brand, model, serial_number, retailer,
    purchase_date, purchase_price, currency
  )
  values (
    v_user_id,
    v_public_id,
    btrim(p_brand),
    btrim(p_model),
    nullif(btrim(coalesce(p_serial_number, '')), ''),
    nullif(btrim(coalesce(p_retailer, '')), ''),
    p_purchase_date,
    p_purchase_price,
    upper(btrim(coalesce(nullif(btrim(p_currency), ''), 'USD')))
  )
  returning id into v_product_id;

  insert into public.warranties (
    product_id, issuer, start_date, end_date, transferability
  )
  values (
    v_product_id,
    nullif(btrim(coalesce(p_warranty_issuer, '')), ''),
    p_warranty_start_date,
    p_warranty_end_date,
    p_transferability
  );

  return query select v_product_id, v_public_id;
end;
$$;

comment on function public.create_product_with_warranty is
  'Creates a product and its warranty in one transaction. Owner comes from '
  'auth.uid(); runs SECURITY INVOKER so RLS still applies to both inserts.';

revoke execute on function public.create_product_with_warranty(
  text, text, date, date, date, text, text, text, numeric, text, text
) from public, anon;

grant execute on function public.create_product_with_warranty(
  text, text, date, date, date, text, text, text, numeric, text, text
) to authenticated;
